# =============================================================================
# GCP Dev — ServiceAccount with Workload Identity
# =============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{@ service_kebab @}-sa"
  annotations:
    iam.gke.io/gcp-service-account: "{@ service_kebab @}-sa-dev@{PROJECT_ID}.iam.gserviceaccount.com"
