apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: "{service}-dev"

resources:
  - ../../base
  - namespace.yaml

images:
  - name: "{service}-predictor"
    newName: "{AWS_ACCOUNT_ID}.dkr.ecr.{REGION}.amazonaws.com/{service}-predictor"
    newTag: "v1.0.0"

patches:
  - path: patch-deployment.yaml
  - path: patch-serviceaccount.yaml
