apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{service}-sa"
  labels:
    app: "{service}"
  annotations:
    # GCP Workload Identity (uncomment for GKE):
    # iam.gke.io/gcp-service-account: {service}-sa@{PROJECT_ID}.iam.gserviceaccount.com

    # AWS IRSA (uncomment for EKS):
    # eks.amazonaws.com/role-arn: arn:aws:iam::{ACCOUNT_ID}:role/{service}-role
