#!/usr/bin/env python3
"""Render thin agent-surface adapters from the canonical manifest.

The source of truth remains:

* `AGENTS.md` for operating protocol, permissions, and invariants.
* `.windsurf/` for canonical rule / skill / workflow bodies.
* `templates/config/agentic_manifest.yaml` for cross-surface indexing.

This script only writes adapter pointers. It never copies full rule,
skill, or workflow bodies into Cursor, Claude, Codex, or future
surfaces.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

try:
    import yaml  # type: ignore
except ImportError:  # pragma: no cover - bootstrap guard
    raise SystemExit("PyYAML is required. Install with: pip install pyyaml")

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST = REPO_ROOT / "templates" / "config" / "agentic_manifest.yaml"


RULE_EXTENSIONS = {
    "cursor": ".mdc",
}

WORKFLOW_ROOT_KEYS = ("workflows", "commands")


def _rel(path: Path) -> str:
    return str(path.relative_to(REPO_ROOT))


def _load_manifest() -> dict[str, Any]:
    data = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit(f"{MANIFEST} did not parse to a mapping")
    return data


def _write(path: Path, body: str, check: bool) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == body:
        return False
    if check:
        print(f"would update {_rel(path)}")
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(body, encoding="utf-8")
    print(f"updated {_rel(path)}")
    return True


def _remove_stale(
    path: Path, expected: set[Path], suffixes: tuple[str, ...], check: bool
) -> bool:
    changed = False
    if not path.exists():
        return changed
    for item in sorted(path.iterdir()):
        if item.is_file() and item.suffix in suffixes and item not in expected:
            changed = True
            if check:
                print(f"would remove {_rel(item)}")
            else:
                item.unlink()
                print(f"removed {_rel(item)}")
    return changed


def _render_skill_index(surface: str, skills: list[dict[str, Any]]) -> str:
    rows = [
        "| Skill | Mode | Canonical |",
        "|-------|------|-----------|",
    ]
    for skill in skills:
        sid = skill["id"]
        rows.append(f"| `{sid}` | `{skill.get('mode', 'AUTO')}` | `{skill['source']}` |")
    table = "\n".join(rows)
    return f"""# {surface.title()} Skills Index

**Adapter surface**: `{surface}`
**Authority**: `AGENTS.md` + `templates/config/agentic_manifest.yaml`

This directory is generated by `scripts/sync_agentic_adapters.py`.
Each skill file is a pointer to the canonical Windsurf `SKILL.md`;
no skill body lives here.

{table}

To change behavior, edit the canonical `.windsurf/skills/<id>/SKILL.md`
and run:

```bash
python3 scripts/sync_agentic_adapters.py
python3 scripts/validate_agentic_manifest.py --strict
```
"""


def _copy_index(
    surface: str, roots: dict[str, str], skills: list[dict[str, Any]], check: bool
) -> bool:
    index_key = "skills_index"
    if index_key not in roots:
        return False
    target = REPO_ROOT / roots[index_key]
    body = _render_skill_index(surface, skills)
    return _write(target, body, check)


def _rule_pointer(surface: str, rid: str, source: str) -> str:
    return f"""# {rid}

**Adapter surface**: `{surface}`
**Authority**: `AGENTS.md` + `templates/config/agentic_manifest.yaml`
**Canonical source**: `{source}`

Read the canonical source in full before acting. This file is a thin
adapter pointer and must not duplicate policy text.

To change this rule, edit `{source}`, update the manifest when needed,
then run:

```bash
python3 scripts/sync_agentic_adapters.py
python3 scripts/validate_agentic_manifest.py --strict
```
"""


def _skill_pointer(surface: str, sid: str, source: str, mode: str) -> str:
    return f"""# {sid}

**Adapter surface**: `{surface}`
**Authority**: `AGENTS.md#Agent Behavior Protocol`
**Mode**: `{mode}`
**Canonical source**: `{source}`

Read `{source}` in full before invoking this skill. The canonical
skill body, trigger conditions, escalation rules, and success criteria
live there.

This file exists only so `{surface}` can discover the skill without
forking `.windsurf/skills/`.
"""


def _workflow_pointer(surface: str, wid: str, source: str, mode: str) -> str:
    return f"""# {wid}

**Adapter surface**: `{surface}`
**Authority**: `AGENTS.md#Agent Behavior Protocol`
**Mode**: `{mode}`
**Canonical source**: `{source}`

Execute this workflow by reading the canonical Windsurf workflow in
full, then applying the same AUTO/CONSULT/STOP protocol and audit
requirements from `AGENTS.md`.

This file is generated as an adapter pointer. Do not add workflow
logic here.
"""


def render(manifest: dict[str, Any], check: bool) -> int:
    surfaces = manifest.get("surfaces") or {}
    changed = False

    for surface, spec in sorted(surfaces.items()):
        if surface == "windsurf" or spec.get("status") != "adapter":
            continue
        roots = spec.get("roots") or {}

        rule_root = roots.get("rules")
        if rule_root:
            root = REPO_ROOT / rule_root
            suffix = RULE_EXTENSIONS.get(surface, ".md")
            expected: set[Path] = set()
            for rule in manifest.get("rules") or []:
                if surface not in (rule.get("surfaces") or []):
                    continue
                path = root / f"{rule['id']}{suffix}"
                expected.add(path)
                changed |= _write(
                    path,
                    _rule_pointer(surface, rule["id"], rule["source"]),
                    check,
                )
            changed |= _remove_stale(root, expected, (".md", ".mdc"), check)

        skill_root = roots.get("skills")
        if skill_root:
            root = REPO_ROOT / skill_root
            expected = set()
            for skill in manifest.get("skills") or []:
                if surface not in (skill.get("surfaces") or []):
                    continue
                path = root / f"{skill['id']}.md"
                expected.add(path)
                changed |= _write(
                    path,
                    _skill_pointer(
                        surface,
                        skill["id"],
                        skill["source"],
                        skill.get("mode", "AUTO"),
                    ),
                    check,
                )
            if "skills_index" in roots:
                expected.add(REPO_ROOT / roots["skills_index"])
            changed |= _remove_stale(root, expected, (".md",), check)
        surface_skills = [
            s
            for s in (manifest.get("skills") or [])
            if surface in (s.get("surfaces") or [])
        ]
        changed |= _copy_index(surface, roots, surface_skills, check)

        workflow_key = next((k for k in WORKFLOW_ROOT_KEYS if k in roots), None)
        if workflow_key:
            root = REPO_ROOT / roots[workflow_key]
            expected = set()
            for workflow in manifest.get("workflows") or []:
                if surface not in (workflow.get("surfaces") or []):
                    continue
                path = root / f"{workflow['id']}.md"
                expected.add(path)
                changed |= _write(
                    path,
                    _workflow_pointer(
                        surface,
                        workflow["id"],
                        workflow["source"],
                        workflow.get("mode", "AUTO"),
                    ),
                    check,
                )
            changed |= _remove_stale(root, expected, (".md",), check)

    return 1 if check and changed else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report drift without writing adapter files.",
    )
    args = parser.parse_args()
    return render(_load_manifest(), check=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
